language: bash

sudo: required
services:
  - docker

before_install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update
  - docker-compose --version
  - docker-compose build
  - docker ps

script:
  - docker-compose -f docker-compose-travis.yml run travis-test-customers

after_script:
  - docker-compose down
