language: bash

sudo: required
services:
  - docker

before_install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update
  - docker-compose --version
  - docker-compose build
  - docker ps

before_script:


script:
  - docker-compose run travis-test-customers
  - docker-compose run travis-test-bookings


after_script:
  - docker-compose down
