version: '3'

services:
  customers:
    build:
      context: ./services/customers
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@customers-db:5432/customers
      - JWT_SECRET=loyaltyprogram
    command: yarn start:dev
    depends_on:
      - customers-db

  customers-db:
    build:
      context: ./services/customers/src/config/db
      dockerfile: Dockerfile
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "6000:8080"
    command: yarn start 
    depends_on:
      - customers

