version: '3.3'

services:
  travis-test-customers:
    image: loyaltyprogrambackendchallenge_customers:latest
    environment:
      - JWT_SECRET=loyaltyprogram
      - PRIVATE_JWT_SECRET=internalloyaltyprogram
      - TEST_DATABASE_URL=postgres://thbhuobq:VDf3b8zaqYHA7K3fwrk8WvFPz6GjOrdi@pellefant.db.elephantsql.com:5432/thbhuobq
    command: yarn test
