version: '3'

services:
  customers:
    build:
      context: ./services/customers
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@customers-db:5432/customers
      - JWT_SECRET=loyaltyprogram
    command: yarn start:dev
    volumes:
      - './services/customers:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - customers-db

  customers-db:
    build:
      context: ./services/customers/src/config/db
      dockerfile: Dockerfile
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  bookings:
    build:
      context: ./services/bookings
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@bookings-db:5432/bookings
    command: yarn start:dev
    volumes:
      - './services/bookings:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - bookings-db
  
  bookings-db:
    build:
      context: ./services/bookings/src/config/db
      dockerfile: Dockerfile
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: yarn start
    volumes:
      - './services/gateway:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - LOG_LEVEL=debug
    depends_on:
      - customers
