version: '3.3'

services:
  customers:
    build:
      context: ./services/customers
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@customers-db:5432/customers
      - TEST_DATABASE_URL=postgres://thbhuobq:VDf3b8zaqYHA7K3fwrk8WvFPz6GjOrdi@pellefant.db.elephantsql.com:5432/thbhuobq
      - JWT_SECRET=loyaltyprogram
      - PRIVATE_JWT_SECRET=internalloyaltyprogram
    command: ["./wait-for-it.sh", "customers-db:5434", "--", "yarn", "start"]
    volumes:
      - './services/customers:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - customers-db

  customers-db:
    build:
      context: ./services/customers/src/config/db
      dockerfile: Dockerfile
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  bookings:
    build:
      context: ./services/bookings
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@bookings-db:5432/bookings
      - CUSTOMER_SERV_URL=http://host.docker.internal:5000
      - TEST_DATABASE_URL=postgres://emvncjld:gpaPb8K7Bpfhzz0x9-L2nFbIlQ2nEzkD@isilo.db.elephantsql.com:5432/emvncjld
      - JWT_SECRET=loyaltyprogram
      - PRIVATE_JWT_SECRET=internalloyaltyprogram
    command: ["./wait-for-it.sh", "bookings-db:5436", "--", "yarn", "start"]
    volumes:
      - './services/bookings:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - bookings-db
  
  bookings-db:
    build:
      context: ./services/bookings/src/config/db
      dockerfile: Dockerfile
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: yarn start
    volumes:
      - './services/gateway:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - PORT=8080
      - JWT_SECRET=loyaltyprogram
      - CUSTOMER_SERVICE_BASE_URL=http://host.docker.internal:5000
      - BOOKING_SERVICE_BASE_URL=http://host.docker.internal:3000
    depends_on:
      - customers
      - bookings
